### ISSUE TITLE
关于使用部分VPN时无法访问Pxer服务器

### ISSUE THREAD

**Issue by simon300000** [FoXZilla/Pxer#13]
我用的运营商是移动，似乎把Pixiv给屏蔽了。
在我用某美国VPN上Pixiv的时候，发现插件无效，后发现是因为使用VPN时无法访问pxer-app.pea3nut.org
于是得关闭VPN然后手动执行代码。

应该不是DNS的问题，用ping发现IP是一样的，只不过开着VPN就无回应。

不知道海外的用户是不是也有一样的问题，还是只是我VPN的问题。

Edit：很玄学的屏蔽，有时能上有时不能上

**Comment by pea3nut** [comment]
pxer服务器使用的是阿里云的VPS，所以国外访问应该是很吃力的。

如果可以的话，添加`pxer-app.pea3nut.org`的白名单规则不进行代理。

另，关于此问题创建了一个 project

**Comment by pea3nut** [comment]
暂时没有钱买国外CDN加速..........

**Comment by simon300000** [comment]
国外DNS。。。怎么想办法搞搞用github.io是否可行？国内Aliyun，国外github

**Comment by pea3nut** [comment]
欸有道理啊！

不过还是等英文版写好了再弄吧，Pxer是入口文件绑定资源URL的，这样要突然要再来2个入口文件有些乱，容我先整理下内部构架......

**Comment by simon300000** [comment]
我刚刚突然想起来，Aliyun的万网 DNS好像可以根据来源智能解析，不清楚能不能实现国外解析到github，国内解析IP
不过你域名是Aliyun的吗→_→？这样似乎不需要改入口文件了

**Comment by pea3nut** [comment]
等学习回来去研究下

**Comment by tuzi3040** [comment]
其实。。。直接托管在github不就好了。。。（国内可能会稍稍慢一点。。。

**Comment by eternal-flame-AD** [comment]
cloudflare也可以的吧。。。。。。

**Comment by eternal-flame-AD** [comment]
看了一下，github.io的站点没有Access-Control-Allow-Origin头，可能会导致无法从pixiv.net加载的问题

**Comment by eternal-flame-AD** [comment]
看了一下github,io有时返回数据没有Access-Control-Allow-Origin头，可能会造成随机性的无法加载

**Comment by eternal-flame-AD** [comment]
可以考虑先上一个试试

**Comment by eternal-flame-AD** [comment]
@tuzi3040 我在自己的fork先开了一个，这几天先看看稳不稳定

**Comment by tuzi3040** [comment]
@eternal-flame-AD 我这边请求过去是有这个header的。

**Comment by eternal-flame-AD** [comment]
我也是绝大多数情况有，我刚刚测试就一次很奇怪的没有

**Comment by eternal-flame-AD** [comment]
不知道是不是偶发现象，过几天如果稳定再考虑吧QWQ

**Comment by tuzi3040** [comment]
（如果要稳定我建议还是用收费服务比较好一点。。。（也不是很贵。。。

**Comment by eternal-flame-AD** [comment]
因为Pxer是免费开源软件所以可能 **专门** 为此购买收费服务的可能性不是很大……
但用现有的服务提供一个海外的节点应该还是可以的

**Comment by tuzi3040** [comment]
（我的意思是开发者自己掏钱。。。_(:3」∠)_
问问花生他那台机子每月跑多少流量好了。。。 @pea3nut

**Comment by eternal-flame-AD** [comment]
这个issue提的问题就是那台机子海外不稳定啊
23333
稳定还干啥要再开

**Comment by pea3nut** [comment]
流量还好。

我有现成的海外节点。一个东京一个洛杉矶，跑的SS，东京的服务器配置还不错。不过我不太清楚怎么配置让一个域名根据不同的情况解析到不同的IP

**Comment by eternal-flame-AD** [comment]
应该用线路设置吧
https://help.aliyun.com/document_detail/35174.html?spm=a2c4g.11186623.6.675.yMHY4T

**Comment by tuzi3040** [comment]
如果觉得流量不多，费用不高的话，套个阿里的全球cdn就好了，也不用每次更新更新两次。也会相对稳定。

**Comment by simon300000** [comment]
我有个Tokyo的服务器 可以贡献一下 用github webhook 更新

**Comment by tuzi3040** [comment]
@pea3nut 能不能开个github page我测试一下aliyun oss+cdn

**Comment by pea3nut** [comment]
Pxer 服务器已全站迁移至海外，问题已修复
