### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by a417943831** [FoXZilla/Pxer#142]
系统 win7
浏览器 搜狗浏览器
pxer开发版

全部画师界面要么无法初始化，要么就提示这样

![3CEFD3C5D6AC3116D90566489B64E956](https://user-images.githubusercontent.com/51856809/59552672-994b8e00-8fbc-11e9-8480-67f676c4f033.png)

Pxer[{ "task":{"url: ttps://ww.pixiv.net/member ilst.php?mode =mediumillust jd=75109253" ], "html": 0, "completed": false,
"type": "manga", "isMultiple": false, "id": *75109253" }, "url": https://www.pixiv.net/member. ilust.php?
mode =medium&illust id=75109253" }]

**Comment by pea3nut** [comment]
https://www.pixiv.net/member_illust.php?mode =medium&illust_id=75109253

你贴的URL少了很多字符，我根据图片打出来URL是无法访问的

报问题参考下模板格式
