### ISSUE TITLE
招聘兼职维护人员

### ISSUE THREAD

**Issue by pea3nut** [FoXZilla/Pxer#144]
## 我需要具备什么

1. 喜欢二次元
2. JavaScript开发能力
3. 加分项：熟悉TypeScript
4. 加分项：浏览器扩展开发经验

## 我需要做什么

1. 维护 & 开发Pxer相关产品线，每月贡献50小时开发人力
2. 社区日常管理

## 我能得到什么

1. 工资1k起，每月底发当月薪水
1. 完成阶段性工作有额外奖金
1. 解雇时额外获得 n+1 个月薪
  （工作4个月 -> 解雇 -> 获得2月薪；工作14个月 -> 解雇 -> 获得3月薪）
1. 来自BAT大厂专业工程师手把手指导
1. 耀眼的开源项目维护经验

## 其他信息

Pxer 目前仅支持中文，在 Pixiv.net 被墙的情况下，每天仍有万级的PV，使用次数每天百余次。平均每3分钟就用一位用户享受了 Pxer 的一键收图

Pxer 开源项目已经有了 500+ 个 Star，并且还在快速增长中

招聘兼职的目的是将 Pxer 国际化，一统P站抓图工具的天下。Pxer 过去曾经很长一段时间是P站抓图的唯一选择，我想将它打造成全球的最佳选择

Pxer 已经维护超过5年了，还有什么比一个维护五年的开源项目更能证明自己的呢？

你可以看下曾经募集小伙伴的 Issue #64 

你可能会问，全球那么多开发者，为什么是Pxer，为什么是你（作者花生）。那么我的回答是：我是全球第二大互联网国，中国，的一线开发者，BAT公司员工。我不仅热爱二次元，而且更关键的是，我有能力做到这一点

---

需要1~2名同学，简历发送至 pea3nut@qq.com

可在本楼进行提问

**Comment by dumuphx** [comment]
你好,我很有兴趣

**Comment by pigpigever** [comment]
楼主还在招人吗？

**Comment by pea3nut** [comment]
@pigpigever 招的

**Comment by pigpigever** [comment]
> @pigpigever 招的

抱歉之前没有看到你的回复，待会我发一份简历给你哈～
