### ISSUE TITLE
求一个抓取个人关注页面下所有画师的图的功能

### ISSUE THREAD

**Issue by sabermakise** [FoXZilla/Pxer#145]
## 你期望增加/修改的功能

求一个抓取个人关注页面下所有画师的图的功能，现在关注的画师超过了两千导致光是一个一个画师的抓图都是个庞大的工作量，所以求一个抓关注的画师的功能

**Comment by pea3nut** [comment]
这个太疯狂了，未来会考虑有个可选的交互页面来抓取？或者在支持同步最新作品到本地的时候可以多选哪些画师会同步
