### ISSUE TITLE
官网pxer.pea3nut.org进不去了，请问这个脚本该去哪里安装啊？

### ISSUE THREAD

**Issue by nanshenyag** [FoXZilla/Pxer#147]
油猴出了bug，重装了油猴，结果发现pxer的脚本没法下载...复制user.js的代码到油猴里也无效，求助，是哪里出了问题？

**Comment by nanshenyag** [comment]
好吧，原来是被墙了，请问何时能够恢复呢

**Comment by pea3nut** [comment]
已经迁移了新服务器，问题应该已经修复
