### ISSUE TITLE
BUG: 无法在作品详情页抓取

### ISSUE THREAD

**Issue by yumehime5** [FoXZilla/Pxer#149]
- Browser Type | 浏览器类型：Google Chrome
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/artworks/77302489
- Bug will happened every times | Bug每次都会复现： Yes

使用时无法获取单个作品页面的信息
1. 点击“LOAD”按钮后：
“当前页面信息”:“页面类型” 为"未知"；
2. 点击“RUN”按钮后：
无法发正常获取作品（一直会处于状态：“抓取页码中”）

**Comment by pea3nut** [comment]
Duplicate for #148
