### ISSUE TITLE
BUG:无法完成抓取

### ISSUE THREAD

**Issue by gototokyo** [FoXZilla/Pxer#150]
- Browser Type | 浏览器类型：
- URL the bug happened | 问题发生的URL：
- Bug will happened every times | Bug每次都会复现： Yes/No
yes
## What did you do | 你做了什么

Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么
点了run以后，一直无法完成抓取。也不显示剩余时间，一直在进行中
Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
请补充内容，你只改了标题，没有任何其他描述我没办法跟进
