### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by kiopkio** [FoXZilla/Pxer#152]
今天突然不论火狐还是谷歌都无法抓图，在作者页面内连一张图都抓不到，提示Cannot read property '0' of null。是因为PX又改版的缘故吗？

**Comment by pea3nut** [comment]
请按照模板填充信息，以便于我追踪修复。

前几天发布了 7.2.1 应该修复了你的问题，如果没有，那么请再开一个 Issue
