### ISSUE TITLE
BUG:解析错误 

### ISSUE THREAD

**Issue by AXIHIXA** [FoXZilla/Pxer#153]
- Browser Type | 浏览器类型：Firefox
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/member.php?id=40196849
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么
运行抓取

## What's expection | 预期的行为是什么
抓取返回所有图片的URL

## What's actually happened | 实际上发生了什么
返回URL数量为0，显示74457686:dom.head.innerHTML.match(...) is null
失败原因：解析错误 
解决方案：再试一次，若问题依旧，请反馈给花生

![图片](https://user-images.githubusercontent.com/32153465/68178708-05726280-ff5b-11e9-8743-de8c73fed293.png)

**Comment by nanshenyag** [comment]
一样，全部解析错误
