### ISSUE TITLE
BUG:搜索页面不能抓取了

### ISSUE THREAD

**Issue by pikalijia** [FoXZilla/Pxer#155]
- Browser Type | 浏览器类型：
- URL the bug happened | 问题发生的URL：
- Bug will happened every times | Bug每次都会复现： Yes/No

## What did you do | 你做了什么

Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
fixed in 7.2.1
