### ISSUE TITLE
BUG:关注作品页解析错误

### ISSUE THREAD

**Issue by Ailitonia** [FoXZilla/Pxer#156]
- Browser Type | 浏览器类型：Chrome 77.0.3865.120
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/bookmark_new_illust.php
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么

正常运行抓取

## What's expection | 预期的行为是什么

获得作品链接

## What's actually happened | 实际上发生了什么

所有抓取均失败
报错Cannot read property '0' of null
![image](https://user-images.githubusercontent.com/41713304/68306750-15b64900-00e5-11ea-9d79-e992c0787f88.png)

附仅抓取第一张作品时console错误信息：
![image](https://user-images.githubusercontent.com/41713304/68307198-d1777880-00e5-11ea-9e7f-6fa4d94e65c2.png)

**Comment by ilikeelf** [comment]
windows 7
firefox 70.0.1
出现了同样的错误

**Comment by pea3nut** [comment]
fixed in 7.2.1
