### ISSUE TITLE
BUG:抓取失败

### ISSUE THREAD

**Issue by jsbydtk** [FoXZilla/Pxer#157]
- Browser Type | 浏览器类型：CHROME
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/member.php?id=8782286
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么       

按照原来一样的方法抓取图片

## What's expection | 预期的行为是什么

抓取成功

## What's actually happened | 实际上发生了什么

抓取失败

**Comment by pea3nut** [comment]
7.2.1 经测试已修复

**Comment by jsbydtk** [comment]
测试使用成功，感谢您的修复。



---原始邮件---
发件人: "花生PeA"<notifications@github.com&gt;
发送时间: 2019年11月9日(星期六) 下午2:37
收件人: "FoXZilla/Pxer"<Pxer@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"jsbydtk"<805618944@qq.com&gt;;
主题: Re: [FoXZilla/Pxer] BUG:抓取失败 (#157)



7.2.1 经测试已修复
