### ISSUE TITLE
BUG: 搜索页面没有对 tag 进行编码导致出错

### ISSUE THREAD

**Issue by xuejianxianzun** [FoXZilla/Pxer#159]
## Basic Info | 基本信息

- Browser Type | 浏览器类型：Chrome
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/search.php?word=Fate%2FGrandOrder
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么

打开网址

## What's expection | 预期的行为是什么

抓取作品

## What's actually happened | 实际上发生了什么

点击“载入”按钮，报错

```
Uncaught (in promise) TypeError: Cannot read property 'total' of undefined
    at native.js:8423

// native.js:8423
resolve(data.illustManga.total)
```

## 问题原因：

标签 `Fate/GrandOrder` 的斜杠未被编码，导致 API 请求的网址错误：

```
https://www.pixiv.net/ajax/search/artworks/Fate/GrandOrder?word=Fate%2FGrandOrder&p=1
```

可以通过对其编码来修复。

**Comment by pea3nut** [comment]
感谢 PR 修复
