### ISSUE TITLE
BUG:抓取数量超过300个作品时会出现抓取失败  获取超时

### ISSUE THREAD

**Issue by hjw199651** [FoXZilla/Pxer#160]
- Browser Type | 浏览器类型：
- URL the bug happened | 问题发生的URL：
- Bug will happened every times | Bug每次都会复现： Yes/No

## What did you do | 你做了什么

Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
请按照模板补充信息，问题应该已经修复。我猜
