### ISSUE TITLE
BUG:用tag进行搜索任务框没有载入按钮

### ISSUE THREAD

**Issue by LEUCHTET** [FoXZilla/Pxer#161]
- Browser Type | 浏览器类型：Chorme
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/tags/%E5%A5%B3%E3%81%AE%E5%AD%90/artworks
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么
什么都没做，就是没有按钮
Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么
希望可以下载tag里的图
Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么
没有按钮无法操作
Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
fixed in 7.3.3
