### ISSUE TITLE
BUG:“抓取XXXX前”不能抓取全部XXXX前的下载地址

### ISSUE THREAD

**Issue by xilingdewodi** [FoXZilla/Pxer#164]
- Browser Type | 浏览器类型：360极速
- URL the bug happened | 问题发生的URL：
- Bug will happened every times | Bug每次都会复现： Yes/No

## What did you do | 你做了什么 抓取77493719前的已关注新作品下载地址

Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么 抓取全部77493719后更新的作品下载地址

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么 对地址的抓取达到77846465就戛然而止了，
上次抓取的10月26号到77846465发布的11月16号之间的作品下载地址没有被成功抓取

Write you info here
在这里补充你的信息

**Comment by xilingdewodi** [comment]
上面的表格不太会填……
简单地说，BUG是
爬了一半就不继续爬了，没有到指定的终止数字就结束了

**Comment by xilingdewodi** [comment]
我全程看了一遍抓取过程，大概知道原因了
执行完2100任务之后就不再继续抓取了，可能是循环写小了

有没有什么办法让它的上限大一点？

**Comment by xilingdewodi** [comment]
多试验了几次，应该是要抓取的数量超过默认上限（100页）导致的，

**Comment by pea3nut** [comment]
请提供如下信息：
- 问题发生的URL
- 是否Bug每次都会复现

**Comment by xilingdewodi** [comment]
> 请提供如下信息：
> 
> * 问题发生的URL
> * 是否Bug每次都会复现


没有URL……昨天试的时候没在意
进行了两次，这个BUG每次都会出现
应该是因为要捕捉的下载地址数量多于默认的上限（100页、2100个任务）
能不能提高上限，或者添加一个捕捉从XXXX开始的设置
