### ISSUE TITLE
BUG:抓取某一个人的图片时，右边的抓取按钮直接不显示，但是如果是某一张图片的时候，就是可以正常使用的。这个问题今天下午才出现，我昨天用的时候还可以。

### ISSUE THREAD

**Issue by Mark000000** [FoXZilla/Pxer#167]
- Browser Type | 浏览器类型：
- URL the bug happened | 问题发生的URL：
- Bug will happened every times | Bug每次都会复现： Yes/No

## What did you do | 你做了什么

Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息

**Comment by xuejianxianzun** [comment]
因为用户页面的 url 变化了，需要适配，不过现在这样确实比以前好看了。
https://www.pixiv.net/users/3869665

**Comment by xuejianxianzun** [comment]
适配完成之前你可以先用我的下载器（逃

**Comment by Mark000000** [comment]
这专业性也太强了吧------------------ 原始邮件 ------------------
发件人: "花生PeA"<notifications@github.com>
发送时间: 2020年1月8日(星期三) 晚上9:58
收件人: "FoXZilla/Pxer"<Pxer@noreply.github.com>;
抄送: "笑红尘"<2207539327@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FoXZilla/Pxer] BUG:抓取某一个人的图片时，右边的抓取按钮直接不显示，但是如果是某一张图片的时候，就是可以正常使用的。这个问题今天下午才出现，我昨天用的时候还可以。 (#167)



Closed #167 via 8513b21.
 
&mdash;
