### ISSUE TITLE
BUG:Pxer7.4.1不能抓取某个画师的画

### ISSUE THREAD

**Issue by Yagami-hayate** [FoXZilla/Pxer#168]
- Browser Type | 浏览器类型：谷歌浏览器
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/users/338751/illustrations
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么
打开画师主页
Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么
准备抓取某个画师的插画
Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么
新版本的pxer没有抓取选项
Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
fixed in 7.4.2
