### ISSUE TITLE
FEAT: 能把编译后的脚本托管到Greasefork或者Github吗？

### ISSUE THREAD

**Issue by thelastfantasy** [FoXZilla/Pxer#169]
![图片](https://user-images.githubusercontent.com/6077584/72676512-3fbcbc00-3ad5-11ea-9299-5c4cb4374d33.png)
https://www.isitdownrightnow.com/pxer.pea3nut.org.html

如图，像现在这样网站访问不了的话脚本就没法用了

编辑：刚试了跑本地版也跑不了，因为网站挂了 https://point.pea3nut.org/sdk/1.0/browser.js 也访问不了

**Comment by pea3nut** [comment]
1. Pxer 服务器挂了确实会导致 Pxer 无法使用。但是这并不一定是坏事
1. Pxer 实际上有 Greasefork 版，可以脱离 Pxer 服务器使用 https://greasyfork.org/zh-CN/scripts/394616-pxer-the-tool-for-pixiv-net
