### ISSUE TITLE
BUG:作品无法抓取，arr is null

### ISSUE THREAD

**Issue by kiopkio** [FoXZilla/Pxer#171]
- Browser Type | 浏览器类型： 	Firefox 55.0b13
- URL the bug happened | 问题发生的URL：任意Pixiv页面
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么

正常运行抓取 

## What's expection | 预期的行为是什么

获得作品链接

## What's actually happened | 实际上发生了什么

所有抓取均失败
报错  (pxID):arr is null

**Comment by pea3nut** [comment]
fixed in 7.5.2
