### ISSUE TITLE
BUG:无法抓取图片

### ISSUE THREAD

**Issue by 913378303** [FoXZilla/Pxer#172]
- Browser Type | 浏览器类型：firefox
- URL the bug happened | 问题发生的URL：https://www.pixiv.net
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么
抓取

Write you info here
在这里补充你的信息 
![GHHH(W QHF9V7S}8C10EZQL](https://user-images.githubusercontent.com/61180895/74714638-e4155800-5265-11ea-90fc-6cf0e1d7335a.png)
![Uploading 54N[AFBGLO{]GTAPW6IY1B9.png…]()

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息

**Comment by 913378303** [comment]
![$GUP @IHL57_GLIDJ7{LBQS](https://user-images.githubusercontent.com/61180895/74714769-35bde280-5266-11ea-891a-fb21ce7fdc36.png)

**Comment by pea3nut** [comment]
我这里非常正常，推测是你中新版本的测试流量了。我的2个号都可以，观察几天看下吧

**Comment by pea3nut** [comment]
fixed in 7.5.2
