### ISSUE TITLE
BUG:无法抓取

### ISSUE THREAD

**Issue by 913378303** [FoXZilla/Pxer#173]
<!-- 请在冒号后填写你的信息 --qq913378303>

- Browser Type | 浏览器类型：firefox Google
- URL the bug happened | 问题发生的URL：https://www.pixiv.net
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么

Write you info here
在这里补充你的信息 
抓取

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 
![GHHH(W QHF9V7S}8C10EZQL](https://user-images.githubusercontent.com/61180895/74714874-69007180-5266-11ea-887c-db7b369abe1f.png)

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息 
![Uploading $GUP[@IHL57_GLIDJ7{LBQS.png…]()

**Comment by pea3nut** [comment]
请补充信息，重开一个 issue ，你开的这个 issue 里面什么也没有
