### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by 913378303** [FoXZilla/Pxer#174]
- Browser Type | 浏览器类型：
- URL the bug happened | 问题发生的URL：
- Bug will happened every times | Bug每次都会复现： Yes/No

## What did you do | 你做了什么

Write you info here
在这里补充你的信息 

## What's expection | 预期的行为是什么

Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
请补充信息，重开一个 issue ，你开的这个 issue 里面什么也没有
