### ISSUE TITLE
BUG:提示解析错误，反复尝试问题依旧

### ISSUE THREAD

**Issue by samlee111** [FoXZilla/Pxer#175]
## Basic Info | 基本信息

- Browser Type | 浏览器类型：Firefox 73.0 (64 位)
- URL the bug happened | 问题发生的URL：https://www.pixiv.net/users/28765728
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么

正常抓取

## What's expection | 预期的行为是什么

抓取图片信息

## What's actually happened | 实际上发生了什么

“部分成功”：74735422:arr is null
解析错误 | 再试一次，若问题依旧，请反馈给花生

![图片](https://user-images.githubusercontent.com/32815796/74731624-4e88c100-5283-11ea-94ff-a47a82ca5088.png)

**Comment by pea3nut** [comment]
我这里非常正常，推测是你中新版本的测试流量了。我的2个号都可以，观察几天看下吧

**Comment by samlee111** [comment]
经过我的一番测试，好像是我的梯子问题？换了个节点，虽然比较慢，但是功能正常使用了……

**Comment by Mioscout** [comment]
我这里Firefox抓不出来，chrome能抓到。Firefox arr is null。
PS。开全局代理也不管用
