### ISSUE TITLE
FEAT: 适配新版 Pixiv 用户界面

### ISSUE THREAD

**Issue by LenKiMo** [FoXZilla/Pxer#176]
## What's localization | 当前的局限性

今天，Pixiv 向一部分用户推送了新版用户界面，这是在去年 11 月就宣布的[改动](https://www.pixiv.net/info.php?id=5401)。此次应该是扩大了推送范围。

![新版界面下的Pxer](https://i.loli.net/2020/02/18/JMFXGj2Bfp3HuZ7.png)

在新界面下，Pxer 的下载条挪到了网页的最上方，与新的 Pixiv 网页设计出现割裂，也未处于正确的位置。

## What's your wishes | 你希望是怎样的

Pxer 应该调整至新版页眉下方、作品区上方的位置。

由于无法判断这次界面推送涉及到的用户范围，因而对此次界面更新应做出的改动可能尚不属于 Bug 修正，故在功能建议中进行投递，提前告知这一新变化，为未来的开发与更新做好准备。

**Comment by pea3nut** [comment]
fixed in 7.5.2
