### ISSUE TITLE
BUG:读取到的原图链接直接访问403，且IDM无法下载

### ISSUE THREAD

**Issue by AOALI123** [FoXZilla/Pxer#191]
- Browser Type | 浏览器类型：CHROME
- URL the bug happened | 问题发生的URL：ALL
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么
扒图
Write you info here
在这里补充你的信息 
扒图以后输出的链接https://i.pximg.net/img-original/img/ 这种的 直接访问都为403
## What's expection | 预期的行为是什么
猜测是P站防盗链没请求头的问题
Write you info here
在这里补充你的信息 

## What's actually happened | 实际上发生了什么

Write you info here
在这里补充你的信息

**Comment by pea3nut** [comment]
是的，直接在浏览器里面打开就是会403，但是你可以直接在复制进下载器里面，请参考 #8 

具体一点的原因，是因为 pixiv.net 做了防盗链，必须在 http header 里面加 referer 才行

**Comment by AOALI123** [comment]
> 是的，直接在浏览器里面打开就是会403，但是你可以直接在复制进下载器里面，请参考 #8
> 
> 具体一点的原因，是因为 pixiv.net 做了防盗链，必须在 http header 里面加 referer 才行

就是我IDM也无法下载才来问的= =

**Comment by pea3nut** [comment]
尝试一下 #8 里面的 EagleGet，如果还不行确保你在下载软件里面设置了正确的代理

**Comment by AOALI123** [comment]
> 是的，直接在浏览器里面打开就是会403，但是你可以直接在复制进下载器里面，请参考 #8
> 
> 具体一点的原因，是因为 pixiv.net 做了防盗链，必须在 http header 里面加 referer 才行

没事了 我以前IDM裸连能下 现在裸连下不了 我挂代理IDM下载正常了

**Comment by Gungnir111** [comment]
> 尝试一下 #8 里面的 EagleGet，如果还不行确保你在下载软件里面设置了正确的代理
如果只是想在pixiv下载图片，代理怎么设置？
