### ISSUE TITLE
期望添加 仅抓取id为x之后的 选项

### ISSUE THREAD

**Issue by cywy** [FoXZilla/Pxer#193]
RT
![Snipaste_2021-03-21_13-31-24](https://user-images.githubusercontent.com/15707136/111894905-c490c600-8a49-11eb-8c5e-6b4946ccb242.png)

**Comment by cywy** [comment]
> RT
> ![Snipaste_2021-03-21_13-31-24](https://user-images.githubusercontent.com/15707136/111894905-c490c600-8a49-11eb-8c5e-6b4946ccb242.png)

理解错了，原来抓取之前就是我的需求，仅抓取id为x之前容易理解成抓取画师更久之前的作品。

**Comment by pea3nut** [comment]
这个文字确实可以改下。。。比如“抓取id为x更新的作品”？这样？其实感觉很难描述

**Comment by pea3nut** [comment]
![image](https://user-images.githubusercontent.com/13781420/144744031-5a65dbab-1fdd-4489-9a4e-d85d3a124756.png)

这样如何？
