### ISSUE TITLE
BUG: 抓取到的图片地址无法访问

### ISSUE THREAD

**Issue by andywang425** [FoXZilla/Pxer#197]
- Browser Type | 浏览器类型：Chrome 90.0.4430.93
- URL the bug happened | 问题发生的URL：所有获取到的图片链接如 https://i.pximg.net/img-original/img/2020/11/20/01/01/43/85776351_p0.jpg
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么
正常操作并成功抓取到了一些图片地址，然后复制到idm里下载。

## What's expection | 预期的行为是什么
idm能正常下载这些链接。

## What's actually happened | 实际上发生了什么
不能下载，把任一链接复制到浏览器中打开显示 `403 Forbidden`。

## 其他
个人感觉应该是p站做了防盗链处理所以没法直接访问。  
我的临时解决办法是把图片地址中`i.pximg.net`这个域名替换成`i.pixiv.cat`，然后就能下载了。
例如：https://i.pixiv.cat/img-original/img/2020/11/20/01/01/43/85776351_p0.jpg

**Comment by pea3nut** [comment]
pixiv.cat 不是P站官方链接，只是个代理，大概率扛不住 Pxer 的流量，因此还是不切换的比较好

P站源链接确实加了防盗链，并且现在也被墙了，如果你用IDE设置代理，应该是能够下载的

**Comment by andywang425** [comment]
我发现是我IDM的代理设置没弄好，切换成使用系统代理之后就正常了。感谢花生的回复
