### ISSUE TITLE
BUG: 国内jsdelivr大面积挂了，pxer无法使用

### ISSUE THREAD

**Issue by WWILLV** [FoXZilla/Pxer#209]
![image](https://user-images.githubusercontent.com/13253768/171674429-018b2c09-1565-4b65-a9f8-51756eaab006.png)
![image](https://user-images.githubusercontent.com/13253768/171678018-176e87b1-9fd7-4cb0-82f2-0f7107ab3ef0.png)

## Basic Info | 基本信息

- Browser Type | 浏览器类型：Chrome
- URL the bug happened | 问题发生的URL：所有的pixiv页面，如 https://www.pixiv.net/users/552160
- Bug will happened every times | Bug每次都会复现： Yes

## What did you do | 你做了什么

nothing

## What's expection | 预期的行为是什么

换个CDN

## What's actually happened | 实际上发生了什么

jsdelivr国内凉了

**Comment by pea3nut** [comment]
换了下，现在应该好了
