### ISSUE TITLE
FEAT: 能否增加替换图片服务器域名的设置

### ISSUE THREAD

**Issue by 707wk** [FoXZilla/Pxer#219]
能否增加替换图片服务器域名的设置, 因为现在爬取的图片地址因为pixiv做了盗链保护, 用迅雷会无法下载, 在浏览器打开图片链接也会显示403. 将服务器域名替换为代理服务器 ( 比如 https://pixiv.cat/reverseproxy.html ) 这种, 迅雷就能正常下载

**Comment by pea3nut** [comment]
很多人用 Pxer 下载成千上万的图片，一般代理服务器应该是扛不住的，只能用源站

关于下载工具可以参考 https://github.com/FoXZilla/Pxer/issues/8

**Comment by 707wk** [comment]
你没懂我意思, 我意思是增加一个输入代理服务器域名的设置. 生成下载链接时判断有设置代理服务器, 就把p站的域名替换为代理服务器的域名, 未设置就使用原始链接

**Comment by pea3nut** [comment]
这个用编辑器自行替换吧，官方提供万一把对方服务器给打挂了被人家找上门就不好了。。。
