### ISSUE TITLE
i.pixiv.net的防盗链导致无法下载

### ISSUE THREAD

**Issue by JsaRut** [FoXZilla/Pxer#224]
请求标头中必须包含Referer: https://www.pixiv.net/ 请求标头才能访问，如果没有该请求标头则403
而翻墙软件没有提供插入HTTP标头的功能，求解决方案

**Comment by pea3nut** [comment]
是的，需要插入防盗链的头，否则会被 403 。有很多工具默认会自动插入，可以看下 #8

**Comment by JsaRut** [comment]
> 是的，需要插入防盗链的头，否则会被 403 。有很多工具默认会自动插入，可以看下 #8

似乎并没有什么，我不用火狐浏览器
QQ旋风已经被腾讯先锋替代，有没有更具体的解决方案。我使用的是IDM

**Comment by pea3nut** [comment]
> > 是的，需要插入防盗链的头，否则会被 403 。有很多工具默认会自动插入，可以看下 #8
> 
> 似乎并没有什么，我不用火狐浏览器 QQ旋风已经被腾讯先锋替代，有没有更具体的解决方案。我使用的是IDM

@JsaRut 我没用过IDM，没办法给你具体的建议。可以加群问问群里用IDM的怎么操作

其他的建议就是，用迅雷或者EagleGet，这俩会自动添加头
