### ISSUE TITLE
QQ浏览器无法启动Pxer

### ISSUE THREAD

**Issue by pea3nut** [FoXZilla/Pxer#23]
## 使用的系统、浏览器、Pxer版本

- Windows 7
- QQ浏览器 9.5.4
- Pxer开发版 

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?id=6996493

## Bug发生时Pxer的状态

无UI显示，无任何提示

## Bug发生的具体情况

Pxer可以成功载入，无任何报错，但是不显示UI

**Comment by pea3nut** [comment]
貌似是vm render的时候出现了问题，情况貌似挺复杂，等有时间再说吧。。。

**Comment by pea3nut** [comment]
应该是computed属性依赖计算的时候嵌套层级太多了的原因

**Comment by Shigma** [comment]
https://caniuse.com/#search=proxy
QQ 浏览器不支持 Proxy

**Comment by pea3nut** [comment]
我记得 master 版本的Pxer没用用到 Proxy

**Comment by eternal-flame-AD** [comment]
master版本报错不一样= =估计还是有啥支持问题

**Comment by eternal-flame-AD** [comment]
@Shigma 这个网站信息好像有点老，我看它说QQ连arrow function也不支持，这个我上次测试了是支持的

**Comment by eternal-flame-AD** [comment]
暂时有以下几点发现：
- QQ浏览器不支持async/await写法
- 问题出在对vm.pxer的跟踪上，只要尝试读取任意prop，vue就会陷入循环依赖，暂时没有找到根源

**Comment by pea3nut** [comment]
测试发现最新版QQ浏览器修复了这个问题
