### ISSUE TITLE
寻求Contributor，为Pxer续一秒！

### ISSUE THREAD

**Issue by pea3nut** [FoXZilla/Pxer#64]
因为种种原因，我不得不放弃Pxer的维护，即使Pxer还未完成它的使命——让P站像拥有Pxer一样好用。

抱歉。

在过去的很长一段时间中，Pxer是世界上唯一一个能work的批量收图工具，所以我在Pxer的官网上写下豪言壮语——可能是目前最好用的P站批量抓图软件。不过我很高兴，Pxer不再是世界上唯一能work的P站收图工具了，所以，这个使命，可以交给其他优秀的同类软件来完成。

四年来，Pxer从一行代码变成几十个文件，从一个简单的`alert()`变成了一个固定在P站的UI面板。Pxer帮助了无数人，但是却从未有过任何盈利行为。

决定不再维护Pxer时，我浑身颤抖，难以相信这个决定真的是自己做出的，难以相信这个事实——Pxer要永远止步在7.0.8了。而在半年前，我还在考虑如何使用TypeScript重构Pxer。

感谢 @eternal-flame-AD 让我看到了一丝曙光——他发送了一个[PR](https://github.com/pea3nut/Pxer/pull/61)（代码合并请求）来帮助Pxer迁移到新版P站。在新版Pxer 7.0.9发布过程中，我甚至一行代码都没有写！

所以，我打算试着相信社区的力量，招募能够一起维护[Pxer](https://github.com/pea3nut/Pxer)或[Pxer官网](https://github.com/pea3nut/pxer-homepage)的开发者。

若你有以下几种想法之一，可以来贡献自己的力量为Pxer续一秒！

- 感兴趣，认为Pxer有价值
- 希望参与开源项目的
- 未参加工作，希望提前体验工作中的 work flow

虽然没有时间维护Pxer，但是基本的 code review 和项目交接还是没有问题的~~

若想参与，可以加QQ群 790688748

**Comment by simon300000** [comment]
> 能word
其实是work？

**Comment by pea3nut** [comment]
算了就这样吧，有Bug能修就修
