### ISSUE TITLE
关于Pxer客户端的种种

### ISSUE THREAD

**Issue by pea3nut** [FoXZilla/Pxer#7]
Pxer客户端相关讨论就整理在这里吧

某位群友写了个貌似不错的P站抓图客户端，对客户端情有独钟的小伙伴可以尝试下→ [renmu123/pixiv](https://github.com/renmu123/pixiv)

**Comment by pea3nut** [comment]
其实，客户端也不是不能写，或者说现在Nodejs的发展壮大，写客户端已经不是难事，而且还可以增加很多现在Pxer7“浏览器插件”的形式所拥有不了的功能

- 动图的打包
- 自动同步
- 自动下载
- 根据设定规则每天自动扒图
- 。。。

但是客户端的功能太强大了，如果开发好，基本上就完全告别了“浏览器插件”的形式了，这个和原先Pxer项目发起的目的有些不同

> 增强Pixiv.net的功能，和Pixiv完美融于一体，成为Pixiv的一部分存在

如果客户端开发出来，就完全成为一个工具，独立于Pixiv了，而不是像现在这样成为Pixiv的一部分

**Comment by pea3nut** [comment]
而且Pxer客户端开发成本目测非常壮观，并不是一个**个人**级的**免费**开源项目可以承担的

当然，如果有dalao三位数三位数软妹币的月捐，花生还是很乐意开发的 : )

**Comment by simon300000** [comment]
有极为微小的Electron开发经验
（我觉得我有可能能帮上忙

**Comment by pea3nut** [comment]
@simon300000 
目前客户端比较需要的功能是：

- Pxer抓取下载地址的自动下载
- 对下载文件进行更名
- 动图的打包

本来的计划是使用node写一个cli的客户端，cli里面跑一个http服务器，浏览器端的Pxer可以把抓取数据直接POST到本地服务器，然后本地cli客户端直接下载图片。UI的话原计划还是用HTML+CSS实现，就是相当于跑了个类似于Express的服务器。

后来考虑了下，貌似开发成本很大，所以就把Pxer调整成一个：
> 为增强pixiv.net而存在的轻量级浏览器插件

我没有用过Electron，不知道如果用Electron开发会怎么样。不过如果你打算写Pxer客户端也是非常欢迎的，Pxer近期会添加插件支持，到时候客户端与浏览器插件直接的接口实现可以作为一个Pxer浏览器端插件来实现（就是项目的`/src/run`目录）

但是插件系统实现起来有些难，卡在插件的崩溃报告实现上了，而且马上我要去360那边学习，10天后估计才能继续开发Pxer的插件系统。

**Comment by SetoKaiba** [comment]
https://chrome.google.com/webstore/detail/mpeoelpkgbnhobojpafdpopjkmeodpaj
其实Pxer已经很好了。。我现在一般都是这个玩意配合Pxer来用，这个玩意在抓取小说，动图什么的，还是挺强大的也是浏览器插件。。
而在批量上，Pxer则更胜一筹。。

**Comment by simon300000** [comment]
我个人使用Pxer有个问题，似乎是因为图片链接有对HTTP Headers的Referer进行检测，所以我用第三方下载工具比如迅雷完全无法下载。
只能使用一些工具通过自定义Referer来下载，比如自己写的这个：[https://github.com/simon300000/Pxer-client/blob/master/test.js](https://github.com/simon300000/Pxer-client/blob/master/test.js)

有在写一个客户端，预计就是输入链接在新窗口打开，然后和浏览器一样的网页浏览，然后链接抓去完之后多个下载的按钮那样。目前就是在看这个下载方式什么的。

**Comment by SetoKaiba** [comment]
我尝试了一下，迅雷好像能过referer的验证。。之前我也以为需要用IDM那类。。后来花生说不用，我也测试了一下。。没问题。。

**Comment by SetoKaiba** [comment]
其实现在H5的话，完全可以把下载器也写进插件里面了。。用blob的方式，类似MEGA网盘的实现方式，类似地，PIXIV DOWNLOADER也是类似的方式。。
但是既然迅雷能过referer，不写具体下载器也没问题。。

**Comment by simon300000** [comment]
然而我的macOS迅雷过不了referer......不知道为什么。

**Comment by simon300000** [comment]
客户端应该还有一个数据库，对下载的东西进行管理（感觉永远做不完）

**Comment by SetoKaiba** [comment]
所以还是考虑跟我说的用h5的下载方式吧。。类似mega网盘的做法。。xhr请求了内容，然后封到a.download里面。。这样还能加作品名，作者名等信息到文件名当中。。
就是可惜a.download的方式不能改变下载的文件夹，不然直接像Pixiv Downloader那样，连作者的名字的文件夹都建好。。pixiv downloader也不是客户端，是chrome的插件，但是他可以下载到下载文件夹的子文件夹，而a.download的方式只能下载到下载文件夹

**Comment by pea3nut** [comment]
记成 Project 卡片了，由于人力原因，可见的未来暂时不做

若有任何其他想法可以继续回复在这个 Issue 中
